export const Data = {
    products: [
        {
            id: '1',
            name: 'Sony Speaker',
            price: 1550,
            image: 'https://th.bing.com/th?q=Sony+Home+Theater&w=120&h=120&c=1&rs=1&qlt=90&cb=1&pid=InlineBlock&mkt=en-WW&cc=NG&setlang=en&adlt=moderate&t=1&mw=247',
        },
        {
            id: '2',
            name: 'Couch Bed',
            price: 1500,
            image: 'https://th.bing.com/th?q=Home+Theater+Couch+Bed&w=120&h=120&c=1&rs=1&qlt=90&cb=1&pid=InlineBlock&mkt=en-WW&cc=NG&setlang=en&adlt=moderate&t=1&mw=247',
        },
        {
                id: '3',
                name: 'Pink Gowns ',
                price: 750,
                image: 'https://th.bing.com/th?q=Hot+Pink+Gowns&w=120&h=120&c=1&rs=1&qlt=90&cb=1&pid=InlineBlock&mkt=en-WW&cc=NG&setlang=en&adlt=moderate&t=1&mw=247',
        },
        {
            id: '4',
            name: 'Samsung Tv ',
            price: 1500,
            image: 'https://th.bing.com/th?q=65+Samsung+Smart+TV&w=120&h=120&c=1&rs=1&qlt=90&cb=1&pid=InlineBlock&mkt=en-WW&cc=NG&setlang=en&adlt=moderate&t=1&mw=247',
        },
        {
            id: '5',
            name: 'Mecedez Benz ',
            price: 23900,
            image: 'https://th.bing.com/th?q=Mercedes-Benz+Convertible+Red&w=120&h=120&c=1&rs=1&qlt=90&cb=1&pid=InlineBlock&mkt=en-WW&cc=NG&setlang=en&adlt=moderate&t=1&mw=247',
        },
        {
            id: '6',
            name: 'Freezer ',
            price: 309.01,
            image: 'https://th.bing.com/th/id/OIP.4zsmYjWXcFrHfC6CzYYaQgAAAA?w=120&h=180&c=7&r=0&o=5&pid=1.7',
        },
        {
            id: '7',
            name: 'Pink Jacket',
            price: 75,
            image: 'https://th.bing.com/th/id/OIP.a7pzOgBdo7n2pG9Ec_IhgQHaJQ?w=147&h=184&c=7&r=0&o=5&pid=1.7',
        },
        {
            id: '8',
            name: 'Power Bike',
            price: 2250,
            image: 'https://th.bing.com/th/id/OIP.16F3tZQdC75LMNCwigZ_fQAAAA?w=132&h=150&c=7&r=0&o=5&pid=1.7',
        },
        {
            id: '9',
            name: 'iphone 13Pro',
            price: 1800,
            image: 'https://th.bing.com/th/id/OIP.TenU4uZO8-Nfw_GyptTNzgAAAA?pid=ImgDet&w=189&h=242&c=7',
        },
        {
            id: '10',
            name: 'Watch',
            price: 139,
            image: 'https://th.bing.com/th/id/OIP.mfy0nrASuWzp6iwtJXoMdQAAAA?w=113&h=180&c=7&r=0&o=5&pid=1.7',
        },
        {
            id: '11',
            name: 'Microwave',
            price: 115,
            image: 'https://th.bing.com/th?q=Small+Microwave+Ovens+Countertop&w=120&h=120&c=1&rs=1&qlt=90&cb=1&pid=InlineBlock&mkt=en-WW&cc=NG&setlang=en&adlt=moderate&t=1&mw=247',
        },
        {
            id: '12',
            name: 'Purple Suit',
            price: 105,
            image: 'https://th.bing.com/th/id/OIP.aUCsEv4gosjyEgZ7yPY6FwHaLO?w=122&h=184&c=7&r=0&o=5&pid=1.7',
        },
        {
            id: '13',
            name: 'Gas Cooker',
            price: 159,
            image: 'https://th.bing.com/th/id/OIP.e10uat83zcV-CT-h6r5whgAAAA?w=115&h=180&c=7&r=0&o=5&pid=1.7',
        },
        {
            id: '14',
            name: 'Travel Bag',
            price: 45,
            image: 'https://th.bing.com/th/id/OIP.B3atmyZ7Rd1KFI6RaTVxBQHaMv?w=116&h=200&c=7&r=0&o=5&pid=1.7',
        },
        {
            id: '15',
            name: 'Sneakers',
            price: 1200,
            image: 'https://th.bing.com/th/id/OIP.z8m_xJbGuiq98w8Iib7uNgAAAA?w=139&h=150&c=7&r=0&o=5&pid=1.7',
        },
        {
            id: '16',
            name: 'Yellow Jacket',
            price: 170,
            image: 'https://th.bing.com/th/id/OIP.q8BILQX2Dg27JlugfTg83QAAAA?w=116&h=180&c=7&r=0&o=5&pid=1.7',
        },
        {
            id: '17',
            name: 'Generator',
            price: 4100,
            image: 'https://th.bing.com/th/id/OIP.gdhB8IC70VMv9LbkQMfffQAAAA?w=127&h=133&c=7&r=0&o=5&pid=1.7',
        },
        {
            id: '18',
            name: 'Fan',
            price: 39,
            image: 'https://th.bing.com/th/id/OIP.iYWTDf1DWnIW2RBPeOYSSQHaQI?w=115&h=199&c=7&r=0&o=5&pid=1.7',
        },
        {
            id: '19',
            name: 'White Shirt',
            price: 50,
            image: 'https://th.bing.com/th/id/OIP.PfnZVpPj6-WjAHXj6Vn8sgAAAA?w=141&h=180&c=7&r=0&o=5&pid=1.7',
        },
        {
            id: '20',
            name: 'Gold Spoon',
            price: 500,
            image: 'https://th.bing.com/th/id/OIP.D40wOQrHz7v2UmiijlVpowAAAA?w=84&h=180&c=7&r=0&o=5&pid=1.7',
        },
        {
            id: '21',
            name: 'Blender',
            price: 150,
            image: 'https://th.bing.com/th/id/OIP.KT4IK6zWSwP1or2XUJ-vxAHaMq?w=115&h=180&c=7&r=0&o=5&pid=1.7'
            ,
        },
        {
            id: '22',
            name: 'Kettle',
            price: 10,
            image: 'https://th.bing.com/th/id/OIP.TKDduEn-8_vTr82jaJyzVQHaJA?w=139&h=180&c=7&r=0&o=5&pid=1.7',
        },
        {
            id: '23',
            name: 'Traffic Light',
            price: 8000,
            image: 'https://th.bing.com/th/id/OIP.GlwoE7OTc2CdHJkfEfVA0gAAAA?w=99&h=180&c=7&r=0&o=5&pid=1.7',
        },
        {
            id: '24',
            name: 'Glass Table',
            price: 90,
            image: 'https://th.bing.com/th/id/OIP.AIiI2pGL3Id71bLY_BhNyAHaE8?w=251&h=180&c=7&r=0&o=5&pid=1.7',
        },
        {
            id: '25',
            name: 'Air Conditioner',
            price: 250,
            image: 'https://th.bing.com/th/id/OIP.avORDxuGkXOxjhjf2UW9swHaE_?w=248&h=180&c=7&r=0&o=5&pid=1.7',
        },
        {
            id: '26',
            name: 'Sweater',
            price: 25,
            image: 'https://th.bing.com/th/id/OIP.ly1dn0JT-4_TcEbrYmluHQAAAA?w=192&h=192&c=7&r=0&o=5&pid=1.7',
        },
        {
            id: '27',
            name: 'Jeans',
            price: 30,
            image: 'https://th.bing.com/th/id/OIP.dv3v1kkiPTehP_nxi9tb0QHaNN?w=191&h=331&c=7&r=0&o=5&pid=1.7',
        },
        {
            id: '28',
            name: 'Shoe',
            price: 45,
            image: 'https://th.bing.com/th/id/OIP.qIR-dvsMengz8S0NWJK4KAHaKb?w=115&h=180&c=7&r=0&o=5&pid=1.7',
        },
        {
            id: '29',
            name: 'Power Oil',
            price: 10,
            image: 'https://th.bing.com/th/id/OIP.9uobx7gi2df1bXIjhGeFBwAAAA?w=173&h=180&c=7&r=0&o=5&pid=1.7',
        },
        {
            id: '30',
            name: 'Ice cream',
            price: 5,
            image: 'https://th.bing.com/th/id/OIP.Y97IA9xQ1_iQFGPTROgyxAHaJt?w=121&h=184&c=7&r=0&o=5&pid=1.7',
        },        
        
    ],
};